name: SCUS_971.01
sha1: 3ff17f4897552e355d0bb8c3abfa5125fe3ff2ef
options:
  platform: ps2
  compiler: EEGCC
  basename: SCUS_971.01
  base_path: ../..
  target_path: disks/SCUS_971.01
  asm_path: asm
  src_path: src
  ld_script_path: config/US/SCUS_971.01.ld
  cache_path: config/US/.splache
  symbol_addrs_path: config/US/symbol_addrs.txt
  reloc_addrs_path: config/US/reloc_addrs.txt
  undefined_funcs_auto_path: config/US/undefined_funcs.txt
  undefined_syms_auto_path: config/US/undefined_syms_auto.txt
  # extensions_path: tools/splat_ext
  nonmatchings_path: nonmatchings

  find_file_boundaries: False
  gp_value: 0x004FEE70
  use_legacy_include_asm: False
  section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
  auto_link_sections: []
  create_undefined_funcs_auto: False
  create_undefined_syms_auto: False
  do_c_func_detection: True
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  ld_bss_is_noload: True
  subalign: 4
  migrate_rodata_to_functions: False
  named_regs_for_c_funcs: False

segments:
  - name: header
    type: databin
    start: 0x0

  - name: main
    type: code
    start: 0x1000
    vram: 0x00100000
    bss_size: 0x255E1C
    align: 4
    subalign: 4
    subsegments:
      # ------------------------------------------------
      # .text segment (C/C++ code)
      # ------------------------------------------------
      - [0x1000, asm, gcc/_crt0]
      - [0x10C0, asm, tmb/ai]
      - [0x92D8, asm, gcc/reg_frame] # C:\TEMP\ccEdaaaa.c - likely autogenerated by G++
      - [0x9350, asm, tmb/attach]
      - [0x9AF8, asm, tmb/attract]
      - [0xABB0, asm, tmb/attracti]
      - [0xC120, asm, tmb/attractped]
      - [0xF0D0, asm, tmb/axle]
      - [0xF8D0, asm, tmb/blimp]
      - [0x101C0, asm, tmb/boss]
      - [0x13378, asm, tmb/burnman]
      - [0x13E50, asm, tmb/camera]
      - [0x16110, asm, tmb/city]
      - [0x161D8, asm, tmb/clapper]
      - [0x16B48, asm, tmb/collis]
      - [0x1D718, asm, tmb/combo]
      - [0x208E8, asm, tmb/db]
      - [0x21020, asm, tmb/death2]
      - [0x21078, asm, tmb/death3]
      - [0x21228, asm, tmb/debris]
      - [0x22298, asm, tmb/destruct]
      - [0x26740, asm, tmb/prison_h] # prison.h inlines
      - [0x26748, asm, tmb/drivein]
      - [0x26BB8, asm, tmb/driver]
      - [0x29A78, asm, tmb/elevator]
      - [0x2A568, asm, tmb/envheli]
      - [0x2B3B8, asm, tmb/ferris]
      - [0x2BCC8, asm, tmb/flipbufferi]
      - [0x2BDF0, asm, tmb/fodder]
      - [0x2CDE0, asm, tmb/fodderdriver]
      - [0x2DE70, asm, tmb/forceField]
      - [0x2E858, asm, tmb/freeway]
      - [0x2F200, asm, tmb/freewaytrain]
      - [0x2FA70, asm, tmb/game]
      - [0x369E8, asm, tmb/gastank]
      - [0x37468, asm, tmb/grim]
      - [0x37C70, asm, tmb/healthstand]
      - [0x38BD8, asm, tmb/helicop]
      - [0x3A580, asm, tmb/heliptool]
      - [0x3A708, asm, tmb/highway]
      - [0x3A908, asm, tmb/highwaydriver]
      - [0x3BAB8, asm, tmb/highwayptool]
      - [0x3BCA0, asm, tmb/hud]
      - [0x43CD8, asm, tmb/hwyloop]
      - [0x43D08, asm, tmb/interact]
      - [0x440F0, asm, tmb/junkjet]
      - [0x45098, asm, tmb/junkyard]
      - [0x45FF0, asm, tmb/launch]
      - [0x525D8, asm, tmb/looptank]
      - [0x53250, asm, tmb/ped]
      - [0x54A20, asm, tmb/pedptool]
      - [0x54D90, asm, tmb/pickup]
      - [0x575D8, asm, tmb/pickupptool]
      - [0x576F8, asm, tmb/player]
      - [0x58A60, asm, tmb/prison]
      - [0x5A948, asm, tmb/prisonShip]
      - [0x5ACA8, asm, tmb/rigiddebris]
      - [0x5C450, asm, tmb/rt]
      - [0x5CD90, asm, tmb/reset]
      - [0x5DA70, asm, tmb/rooftop]
      - [0x5EE98, asm, tmb/shadow]
      - [0x5F5F8, asm, tmb/shell]
      - [0x64500, asm, tmb/shelloverlays]
      - [0x69180, asm, tmb/skidmark]
      - [0x6A960, asm, tmb/smasher]
      - [0x6B040, asm, tmb/sound]
      - [0x880A0, asm, tmb/suburb]
      - [0x88530, asm, tmb/susp]
      - [0x89BB0, asm, tmb/tankcar]
      - [0x8A040, asm, tmb/thunderstorm]
      - [0x8A580, asm, tmb/timberdebris]
      - [0x8AC90, asm, tmb/tire]
      - [0x8CCE8, asm, tmb/tmmemcard]
      - [0x8DD68, asm, tmb/trafficdirector]
      - [0x8F948, asm, tmb/ui]
      - [0x9F358, asm, tmb/uimemcard]
      - [0xA4B98, asm, tmb/vehicle]
      - [0xB18E0, asm, tmb/watow]
      - [0xB1D60, asm, tmb/weap]
      - [0xBBCA0, asm, tmb/989snd]
      - [0xBDEC8, asm, tmb/aa]
      - [0xBE530, asm, tmb/animChan]
      - [0xC0F98, asm, tmb/bound]
      - [0xC10D0, asm, tmb/CsColor]
      - [0xC1248, asm, tmb/dbs] # this file has C++ STL inlines
      - [0xC2310, asm, tmb/disp]
      - [0xC2B20, asm, tmb/drawc]
      - [0xC31D0, asm, tmb/file]
      - [0xC46F8, asm, tmb/fog]
      - [0xC4E48, cpp, tmb/font]
      - [0xC5C38, asm, tmb/hd]
      - [0xC9D40, asm, tmb/hdcar]
      - [0xCFC90, asm, tmb/hdhat]
      - [0xD1288, asm, tmb/hdlos]
      - [0xD38E8, asm, tmb/hierc]
      - [0xD61E0, asm, tmb/hiertrav] # hiertrav.s - hand-coded ASM
      - [0xD6C08, asm, tmb/hoserInfo]
      - [0xD71A8, asm, tmb/ieGs]
      - [0xD7A78, asm, tmb/ilnk]
      - [0xD7BC0, asm, tmb/input]
      - [0xDAC30, asm, tmb/LightVolume]
      - [0xDB1E8, asm, tmb/mathf]
      - [0xDDB90, asm, tmb/mathv0] # Might need to be `hasm`, seems to be inline assembly.
      - [0xDDDC8, asm, tmb/memCard]
      - [0xDFD00, asm, tmb/memorystack]
      - [0xDFD38, asm, tmb/movie]
      - [0xE0890, asm, tmb/particle]
      - [0xEAAD8, asm, tmb/pkt]
      - [0xEBAE8, asm, tmb/pkta] # pkta.s HASM
      - [0xEC030, asm, tmb/plight]
      - [0xED2C8, asm, tmb/read]
      - [0xED5F8, asm, tmb/readbuf]
      - [0xED708, asm, tmb/resetcom]
      - [0xEDF60, asm, tmb/rigidbody]
      - [0xEF1A8, asm, tmb/smooth]
      - [0xEF8D8, asm, tmb/strfile]
      - [0xEFAD8, asm, tmb/sys] # sys.s HASM
      - [0xEFB20, asm, tmb/td]
      - [0xF03A0, asm, tmb/terrain]
      - [0xF7788, asm, tmb/timer]
      - [0xF7B58, asm, tmb/tod]
      - [0xF9868, asm, tmb/texm] # has C++ STL inlines
      - [0xFC9F0, asm, tmb/texa] # texa.s HASM
      - [0xFCD08, asm, tmb/utilities]
      - [0xFDA00, asm, tmb/view]
      - [0xFF590, asm, tmb/videodec]
      - [0xFFD98, asm, tmb/vobuf]
      - [0xFFF78, asm, tmb/zip]
      - [0x101C08, asm, tmb/audiodec]
      - [0x102310, asm, tmb/bsp]
      - [0x102708, asm, tmb/charanim]
      - [0x102CD0, asm, tmb/ctx]
      - [0x102D70, asm, tmb/CsList]
      - [0x102E98, asm, tmb/hier] # hier.s HASM
      - [0x103160, asm, tmb/vibuf] # TODO: this is probably two TUs
      # SDK TUs start here
      - [0x1043B0, asm, sdk/libgraph/graphdev]
      - [0x105E80, asm, sdk/libpad/libpad]
      - [0x107228, asm, sdk/libmtap/libmtap]
      - [0x1076F8, asm, sdk/libmc/libmc]
      - [0x1088E0, asm, sdk/libmpeg/pack]
      - [0x1096B8, asm, sdk/libmpeg/mpeg]
      - [0x10A278, asm, sdk/libmpeg/init]
      - [0x10AE50, asm, sdk/libmpeg/defhandler]
      - [0x10AE70, asm, sdk/libmpeg/mpc]
      - [0x10FBF0, asm, sdk/libmpeg/csc]
      - [0x110098, asm, sdk/libmpeg/bit]
      - [0x1102A8, asm, sdk/libipu/libipu]
      - [0x110660, asm, sdk/libipu/ipuinit]
      - [0x1108F8, asm, sdk/liblgdev/liblgdev]
      - [0x1117B8, asm, sdk/libcdvd/eecdvd]
      # C runtime TUs start here
      - [0x114530, asm, newlib/libm/math/sf_atan]
      - [0x1147D8, asm, newlib/libm/math/sf_ceil]
      - [0x1148B0, asm, newlib/libm/math/sf_cos]
      - [0x114998, asm, newlib/libm/math/sf_fabs]
      - [0x1149B8, asm, newlib/libm/math/sf_floor]
      - [0x114AA0, asm, newlib/libm/math/sf_sin]
      - [0x114B90, asm, newlib/libm/math/w_sqrt]
      - [0x114CA0, asm, newlib/libm/math/wf_atan2]
      - [0x114DC8, asm, newlib/libm/math/wf_pow]
      - [0x1152D0, asm, newlib/libm/math/wf_sqrt]
      - [0x1153E8, asm, newlib/libm/math/e_sqrt]
      - [0x1156F0, asm, newlib/libm/math/ef_atan2]
      - [0x1159D8, asm, newlib/libm/math/ef_pow]
      - [0x116268, asm, newlib/libm/math/ef_rem_pio2]
      - [0x116648, asm, newlib/libm/math/ef_sqrt]
      - [0x116780, asm, newlib/libm/math/kf_cos]
      - [0x1168D8, asm, newlib/libm/math/kf_rem_pio2]
      - [0x117228, asm, newlib/libm/math/kf_sin]
      - [0x117330, asm, newlib/libm/math/s_isnan]
      - [0x117368, asm, newlib/libm/math/s_matherr]
      - [0x117390, asm, newlib/libm/math/s_rint]
      - [0x117590, asm, newlib/libm/math/sf_finite]
      - [0x1175B8, asm, newlib/libm/math/sf_isnan]
      - [0x1175E0, asm, newlib/libm/math/sf_scalbn]
      - [0x117740, asm, newlib/libm/math/sf_copysign]
      - [0x117770, asm, gcc/libgcc2]
      - [0x118B48, asm, gcc/dp-bit]
      - [0x119858, asm, gcc/cp/exception] # exception.cc
      - [0x119F98, asm, gcc/fp-bit]
      - [0x11AB78, asm, gcc/frame]
      - [0x11BBA8, asm, gcc/cp/new] # new.cc
      - [0x11BC58, asm, gcc/cp/new2] # new2.cc
      - [0x11BCD0, asm, gcc/cp/new1] # new1.cc
      - [0x11BDF8, asm, gcc/cp/tinfo] # tinfo.cc
      - [0x11C4C8, asm, gcc/cp/tinfo2] # tinfo2.cc
      - [0x11D248, asm, newlib/libc/stdlib/abort]
      - [0x11D268, asm, newlib/libc/stdlib/atexit]
      - [0x11D300, asm, newlib/libc/errno/errno]
      - [0x11D310, asm, newlib/libc/stdio/findfp]
      - [0x11D568, asm, newlib/libc/stdio/fwalk]
      - [0x11D600, asm, newlib/libc/stdlib/malloc]
      - [0x11D638, asm, newlib/libc/stdlib/mallocr]
      - [0x11E008, asm, newlib/libc/machine/r5900/memcpy] # memcpy.S HASM
      - [0x11E0B8, asm, newlib/libc/machine/r5900/memset] # memset.S HASM
      - [0x11E178, asm, newlib/libc/stdlib/mlock]
      - [0x11E188, asm, newlib/libc/stdio/printf]
      - [0x11E218, asm, newlib/libc/stdlib/rand]
      - [0x11E258, asm, newlib/libc/reent/sbrkr]
      - [0x11E2B8, asm, newlib/libc/signal/signal]
      - [0x11E608, asm, newlib/libc/reent/signalr]
      - [0x11E688, asm, newlib/libc/stdio/sprintf]
      - [0x11E760, asm, newlib/libc/stdio/stdio]
      - [0x11E8D0, asm, newlib/libc/machine/r5900/strcat] # strcat.S HASM
      - [0x11E9FC, asm, newlib/libc/machine/r5900/strchr] # strchr.S HASM
      - [0x11EB8C, asm, newlib/libc/machine/r5900/strcmp] # strcmp.S HASM
      - [0x11ECD0, asm, newlib/libc/machine/r5900/strcpy] # strcpy.S HASM
      - [0x11EDE4, asm, newlib/libc/machine/r5900/strlen] # strlen.S HASM
      - [0x11EF20, asm, newlib/libc/machine/r5900/strncat] # strncat.S HASM
      - [0x11F0D0, asm, newlib/libc/machine/r5900/strncpy] # strncpy.S HASM
      - [0x11F290, asm, newlib/libc/stdio/vfprintf]
      - [0x120BB0, asm, newlib/libc/reent/writer]
      - [0x120C10, asm, newlib/libc/stdio/wsetup]
      - [0x120D20, asm, newlib/libc/reent/closer]
      - [0x120D78, asm, newlib/libc/stdlib/dtoa]
      - [0x122160, asm, newlib/libc/stdio/fflush]
      - [0x122268, asm, newlib/libc/stdlib/mallocr_2] # TODO: why is this a different TU?
      - [0x1226F8, asm, newlib/libc/stdio/fvwrite]
      - [0x122AD0, asm, newlib/libc/locale/locale]
      - [0x122BC0, asm, newlib/libc/reent/lseekr]
      - [0x122C20, asm, newlib/libc/stdio/makebuf]
      - [0x122D70, asm, newlib/libc/stdlib/mbtowc_r]
      - [0x122DAC, asm, newlib/libc/machine/r5900/memchr] # memchr.S HASM
      - [0x122E8C, asm, newlib/libc/machine/r5900/memmove] # memmove.S HASM
      - [0x122F90, asm, newlib/libc/stdlib/mprec]
      - [0x123FB0, asm, newlib/libc/reent/readr]
      - [0x124010, asm, newlib/libm/math/s_isinf]
      - [0x124058, asm, newlib/libc/stdlib/mallocr_3] # TODO: why is this a different TU?
      - [0x124118, asm, newlib/libc/reent/fstatr]
      # Start of SDK libs again
      - [0x124180, asm, sdk/libkernl/klib] # klib.s HASM
      - [0x124A10, asm, sdk/libkernl/glue]
      - [0x124DB8, asm, sdk/libkernl/cache]
      - [0x125028, asm, sdk/libkernl/intr]
      - [0x125360, asm, sdk/libkernl/thread]
      - [0x1256C0, asm, sdk/libkernl/tty]
      - [0x125BE0, asm, sdk/libkernl/kprintf]
      - [0x126620, asm, sdk/libkernl/sifcmd]
      - [0x126D80, asm, sdk/libkernl/sifrpc]
      - [0x127CA8, asm, sdk/libkernl/filestub]
      - [0x1289C0, asm, sdk/libkernl/iopheap]
      - [0x128C20, asm, sdk/libkernl/eeloadfile]
      - [0x1294F0, asm, sdk/libkernl/iopreset]
      - [0x129790, asm, sdk/libkernl/deci2]
      - [0x129970, asm, gcc/libgcc2_2] # TODO: why is this a different TU?
      - [0x12B2C8, asm, newlib/libc/machine/r5900/memcmp] # memcmp.S HASM
      # ------------------------------------------------
      # .vutext segment
      # ------------------------------------------------
      - [0x12B360, data, vutext]
      # ------------------------------------------------
      # .data segment
      # ------------------------------------------------
      - [0x135D00, data]
      # ------------------------------------------------
      # .rodata segment
      # ------------------------------------------------
      - [0x3E5780, rodata]
      # ------------------------------------------------
      # .gcc_except_table segment
      # ------------------------------------------------
      - [0x3F7D80, rodatabin, gcc_except_table]
      # ------------------------------------------------
      # .lit4 segment
      # ------------------------------------------------
      - [0x3F7E80, lit4]
      # ------------------------------------------------
      # .sdata segment
      # ------------------------------------------------
      - [0x3FB900, sdata]
      - [0x3FBB3C, sdata, tmb/launch]
      - [0x3FBC14, sdata]
      - [0x3FC850, sdata, tmb/hd]
      - [0x3FC86C, sdata, tmb/hdcar]
      - [0x3FC888, sdata, tmb/hdhat]
      - [0x3FC88C, sdata, tmb/hdlos]
      - [0x3FC8A4, sdata]
      # ------------------------------------------------
      # .sbss segment
      # ------------------------------------------------
      - {start: 0x3FCD00, type: sbss, vram: 0x004FBD00 }
      # ------------------------------------------------
      # .bss segment
      # ------------------------------------------------
      - {start: 0x3FCD00, type: bss, vram: 0x004FC000 }
  # ------------------------------------------------
  # Debug info segments
  # ------------------------------------------------
  - [0x3FCD00, databin] # padding to .reginfo
  - [0x3FCD14, databin] # .reginfo
  - [0x3FCD2C, databin] # .mdebug
  - [0x4F2F70, databin] # .DVP_ovlytab
  - [0x4F3030, databin] # .DVP_ovlystrtab
  - [0x4F324C, databin] # .DVP_overlay__0x0_13651_30_0
  - [0x4F3A4C, databin] # .DVP_overlay__unknvma_31515_777_1
  - [0x4F424C, databin] # .DVP_overlay__unknvma_31515_1315_2
  - [0x4F4A4C, databin] # .DVP_overlay__unknvma_31515_1747_3
  - [0x4F524C, databin] # .DVP_overlay__unknvma_31515_2637_4
  - [0x4F5A4C, databin] # .DVP_overlay__unknvma_31515_3061_5
  - [0x4F5A6C, databin] # .DVP_overlay__0x0_28451_38_0
  - [0x4F626C, databin] # .DVP_overlay__unknvma_61707_538_1
  - [0x4F6A6C, databin] # .DVP_overlay__unknvma_61707_1141_2
  - [0x4F726C, databin] # .DVP_overlay__unknvma_61707_1760_3
  - [0x4F7A6C, databin] # .DVP_overlay__unknvma_61707_2182_4
  - [0x4F826C, databin] # .DVP_overlay__unknvma_61707_2668_5
  - [0x4F8A6C, databin] # .DVP_overlay__unknvma_61707_3109_6
  - [0x4F8F8C, databin] # .DVP_overlay__0x0_27859_18_0
  - [0x4F96BC, databin] # .DVP_overlay__0x0_13171_23_0
  - [0x4F9EBC, databin] # .DVP_overlay__unknvma_31035_529_1
  - [0x4FA2F4, databin] # .shstrtab
  - [0x4FA5AC, databin] # .elfSectionHeaders
  - [0x4FAB4C, databin] # .symtab
  - [0x518A8C, databin] # .strtab
  - [0x53C14F] # End of file
